server:
  port: 9004
  servlet:
    context-path: /redis
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
        max-wait: 2000
