server:
  servlet:
    context-path: /shiro
  port: 9006
shiro:
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
  unauthorizedUrl: /unauthorizedurl
  web:
    enabled: true
  successUrl: /index
  loginUrl: /login
