server:
  servlet:
    context-path: /thymeleaf
  port: 9001
spring:
  thymeleaf:
    # 文件编码为 UTF-8
    encoding: UTF-8
    # 开发中需要看到实时数据设置为 false, 可在生产设置为 true
    cache: false
    # 模板默认位置为 templates，可更改到指定路径
    prefix: classpath:/templates/
    mode: HTML
    enabled: true